<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="MarkdownSnippets.MsBuild" Version="28.4.4" />
    <PackageVersion Include="Microsoft.CodeAnalysis.Analyzers" Version="3.11.0" Pinned="true" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="4.9.2" Pinned="true" />
    <PackageVersion Include="Microsoft.CodeAnalysis.VisualBasic" Version="4.9.2" Pinned="true" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
    <PackageVersion Include="Polyfill" Version="11.4.0" />
    <PackageVersion Include="ProjectDefaults" Version="1.0.181" />
    <PackageVersion Include="Sbom" Version="0.2.0" />
    <PackageVersion Include="Verify" Version="33.1.4" />
    <PackageVersion Include="Verify.DiffPlex" Version="3.3.1" />
    <PackageVersion Include="Verify.XunitV3" Version="33.1.4" />
    <PackageVersion Include="xunit.v3" Version="4.0.1" />
    <PackageVersion Include="Argon" Version="0.37.0" />
    <PackageVersion Include="DiffEngine" Version="20.5.1" />
    <PackageVersion Include="EmptyFiles" Version="8.19.0" />
    <PackageVersion Include="SimpleInfoName" Version="3.2.0" />
  </ItemGroup>
</Project>
